# Generated by Django 5.1.6 on 2025-05-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='token_group',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
