# Generated by Django 5.1.6 on 2025-05-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatgroup_token_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.firebaseuser'),
        ),
    ]
