# Generated by Django 5.1.6 on 2025-05-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sessions_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='fid',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
