# Generated by Django 5.1.6 on 2025-05-10 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sessions_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='api.sessions'),
        ),
        migrations.AlterField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.firebaseuser'),
        ),
    ]
